cli:
  - changed-files:
    - any-glob-to-any-file:
      - 'Sources/CLI/**'
      - 'Sources/ContainerCommands/**'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**'

ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'