version: 1
builder:
  configs:
    -
      documentation_targets:
        - ContainerAPIService
        - ContainerAPIClient
        - ContainerSandboxService
        - ContainerSandboxServiceClient
        - ContainerNetworkService
        - ContainerNetworkServiceClient
        - ContainerImagesService
        - ContainerImagesServiceClient
        - ContainerResource
        - ContainerLog
        - ContainerPlugin
        - ContainerXPC
        - TerminalProgress
      swift_version: '6.2'
